
name: build_cygwin

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: cmake make gcc-g++ github iconv-devel zlib-devel clang llvm zip unzip curl sed libpcre-devel libpcre2-devel liblzma-devel gettext gettext-devel libtool automake autoconf po4a

      - name: Clone source code
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          git clone --recurse-submodules https://github.com/affggh/erofs-utils_cygwin.git -b dev erofs
          cd erofs
          # for extract.erofs
          git clone https://github.com/sekaiacg/erofs-utils erofs-utils
          
      - name: Patch @sekaiacg repo
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          cd erofs/erofs-utils/extract
          for i in $(ls *.cpp); do
            sed "s/\[\[unlikely\]\]//g" -i $i && echo Patch $i
          done
          sed -i "s/symlink(buf, filePath)/cyglink(buf, filePath)/g" ExtractHelper.cpp && echo 'Patch symlink -> cyglink'
          sed -i "/LOGCW(\"failed to set times: %s\", path);/d" ExtractHelper.cpp && echo "Patch delete failed to set times"
          sed -i "s/#ifdef WITH_ANDROID/#include \"cyglink.h\"\n#ifdef WITH_ANDROID/" ExtractHelper.cpp && echo patch cyglink
          
      - name: Install liblzma
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          cd erofs/xz
          ./autogen.sh || true
          ./configure
          make -j$(nproc --all) && make install

      - name: Install pcre
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
            cd erofs/pcre
            ./configure
            make && make install

      - name: Generate custom header file
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          cd erofs
          printf "#define PACKAGE_VERSION \"%s\"\n" "$(sed -n '1p' VERSION | tr -d '\n')" > erofs-utils-version.h
          if [ -f "erofs-utils-version.h" ]; then
            echo "Success generated erofs-utils-version.h"
          else
            echo "Failed generated erofs-utils-version.h"
            exit 1
          fi
          find /usr/lib -name liblzma*
          find /usr/local/lib -name liblzma*
          find /lib -name liblzma*

      - name: Building
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          cd erofs
          # build
          make -j$(nproc --all) LDFLAGS="-static -L/usr/local/lib"
          # output
          ls -al bin
          
      - name: Repack out
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          cd erofs
          zip -r erofs_cygwin64.zip bin
          
      - name: Upload output to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: C:\tools\cygwin\home\runneradmin\erofs\erofs_cygwin64.zip
          name: "erofs-${{ github.run_number }}-cygwin64"
          tag: "erofs-${{ github.run_number }}-cygwin64"
          bodyFile: C:\tools\cygwin\home\runneradmin\erofs\VERSION
          token: ${{ secrets.GITHUB_TOKEN }}
